<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Authentication Language Lines
    |--------------------------------------------------------------------------
    |
    | Translations for authentication - Cleaned version
    |
    */

    'login' => 'Sign in',
    'register' => 'Sign up',
    'logout' => 'Logout',

    'name' => 'Username',
    'email' => 'Email',
    'password' => 'Password',
    'confirm_password' => 'Confirm Password',
    'remember' => 'Remember me',

    'site' => [
        'name' => 'Site name',
        'default_name' => 'MC-CMS',
        'default_description' => 'Modern Content Management System for Game Servers',
    ],

    'features' => [
        'minecraft' => 'Minecraft Server',
        'management' => 'Content Management',
        'admin' => 'Admin Panel',
    ],

    'description' => [
        'main' => '{siteName} makes managing your Minecraft server easier than ever. Complete control over users, shop, and content.',
    ],

    'powered_by' => 'Powered by {siteName}',

    'password_placeholder' => '••••••••',

    'failed' => 'These credentials do not match our records.',
    'throttle' => 'Too many login attempts. Please try again in :seconds seconds.',

    'mail' => [
        'reset' => [
            'subject' => 'Reset Password',
            'line1' => 'You are receiving this email because we received a password reset request for your account.',
            'action' => 'Reset Password',
            'line2' => 'This password reset link will expire in :count minutes.',
            'line3' => 'If you did not request a password reset, no further action is required.',
        ],
        'verify' => [
            'subject' => 'Verify Email Address',
            'line1' => 'Please click the button below to verify your email address.',
            'action' => 'Verify Email Address',
            'line2' => 'If you did not create an account, no further action is required.',
        ],
    ],

    'no_account' => "Don't have an account?",
    'have_account' => 'Already have an account?',
    'continue_with' => 'Or continue with',
    'sign_in_with' => 'Sign in with',
    'sign_up_with' => 'Sign up with',
    'google' => 'Google',
    'discord' => 'Discord',
    'terms_agree' => 'By continuing, you agree to our',
    'terms_agree_register' => 'By signing up, you agree to our',
    'terms_of_service' => 'Terms of Service',
    'privacy_policy' => 'Privacy Policy',
    'and' => 'and',
    'join_community' => 'Join our community',
    'community_message' => 'makes managing your Minecraft server easier than ever. Complete control over users, shop, and content.',

    '2fa' => [
        'title' => 'Two-Factor Authentication',
        'description' => 'Enter the 6-digit code from your authenticator app',
        'enter_code' => 'Verification code',
        'verify' => 'Verify',
        'verifying' => 'Verifying...',
        'back' => 'Back to login',
        'instruction_title' => 'Open your authenticator app',
        'instruction' => 'Enter the 6-digit code generated by Google Authenticator, Authy or a similar app.',
        'recovery_title' => 'Recovery codes',
        'recovery' => 'If you cannot access your authenticator app, you can use a recovery code.',
        'digits' => 'digits',
        'secure_title' => 'Secured by 2FA',
        'secure_message' => 'Your account is protected with an extra layer of security.',
        'protected' => 'is secured with two-factor authentication.',
    ],
];
