/**
 * Dynamic icon component for navigation items
 * Maps icon names (strings) to actual icon components from @tabler/icons-react
 */
import {
  IconBrandTabler,
  IconUserBolt,
  IconUsers,
  IconServer,
  IconHome,
  IconShield,
  IconBan,
  IconDownload,
  IconList,
  IconMenu2,
  IconPlug,
  IconPalette,
  IconFileText,
  IconSettings,
  IconFolder,
  IconDatabase,
  IconShoppingBag,
  IconShoppingCart,
  IconPackage,
  IconNews,
  IconEdit,
  IconTrash,
  IconPlus,
  IconX,
  IconCheck,
  IconRefreshCw,
  IconAlertCircle,
  IconChevronDown,
  IconChevronRight,
  IconChevronLeft,
  IconExternalLink,
  IconCopy,
  IconClipboard,
  IconSearch,
  IconFilter,
  IconCalendar,
  IconClock,
  IconUser,
  IconMail,
  IconLock,
  IconUnlock,
  IconKey,
  IconGlobe,
  IconLink,
  IconImage,
  IconVideo,
  IconMusic,
  IconFile,
  IconFolderOpen,
  IconArchive,
  IconUpload,
  IconDownloadCloud,
  IconZoomIn,
  IconZoomOut,
  IconMaximize,
  IconMinimize,
  IconSettings2,
  IconTools,
  IconWrench,
  IconHammer,
  IconBuild,
  IconCode,
  IconTerminal,
  IconCloud,
  IconWifi,
  IconBluetooth,
  IconUsb,
  IconCpu,
  IconHardDrive,
  IconHardDrives,
  IconMemory,
  IconMicrochip,
  IconActivity,
  IconAnalytics,
  IconChartBar,
  IconChartLine,
  IconTrendingUp,
  IconTrendingDown,
} from '@tabler/icons-react';

// Icon name mapping for common icons
const ICON_MAP: Record<string, React.ComponentType<{ className?: string }>> = {
  BrandTabler: IconBrandTabler,
  UserBolt: IconUserBolt,
  Users: IconUsers,
  Server: IconServer,
  Home: IconHome,
  Shield: IconShield,
  Ban: IconBan,
  Download: IconDownload,
  List: IconList,
  Menu2: IconMenu2,
  Plug: IconPlug,
  Palette: IconPalette,
  FileText: IconFileText,
  Settings: IconSettings,
  Folder: IconFolder,
  Database: IconDatabase,
  ShoppingBag: IconShoppingBag,
  ShoppingCart: IconShoppingCart,
  Package: IconPackage,
  News: IconNews,
  Edit: IconEdit,
  Trash: IconTrash,
  Plus: IconPlus,
  X: IconX,
  Check: IconCheck,
  RefreshCw: IconRefreshCw,
  AlertCircle: IconAlertCircle,
  ChevronDown: IconChevronDown,
  ChevronRight: IconChevronRight,
  ChevronLeft: IconChevronLeft,
  ExternalLink: IconExternalLink,
  Copy: IconCopy,
  Clipboard: IconClipboard,
  Search: IconSearch,
  Filter: IconFilter,
  Calendar: IconCalendar,
  Clock: IconClock,
  User: IconUser,
  Mail: IconMail,
  Lock: IconLock,
  Unlock: IconUnlock,
  Key: IconKey,
  Globe: IconGlobe,
  Link: IconLink,
  Image: IconImage,
  Video: IconVideo,
  Music: IconMusic,
  File: IconFile,
  FolderOpen: IconFolderOpen,
  Archive: IconArchive,
  Upload: IconUpload,
  DownloadCloud: IconDownloadCloud,
  ZoomIn: IconZoomIn,
  ZoomOut: IconZoomOut,
  Maximize: IconMaximize,
  Minimize: IconMinimize,
  Settings2: IconSettings2,
  Tools: IconTools,
  Wrench: IconWrench,
  Hammer: IconHammer,
  Build: IconBuild,
  Code: IconCode,
  Terminal: IconTerminal,
  Cloud: IconCloud,
  Wifi: IconWifi,
  Bluetooth: IconBluetooth,
  Usb: IconUsb,
  Cpu: IconCpu,
  HardDrive: IconHardDrive,
  HardDrives: IconHardDrives,
  Memory: IconMemory,
  Microchip: IconMicrochip,
  Activity: IconActivity,
  Analytics: IconAnalytics,
  ChartBar: IconChartBar,
  ChartLine: IconChartLine,
  TrendingUp: IconTrendingUp,
  TrendingDown: IconTrendingDown,
};

/**
 * Get an icon component by name
 * Returns a default icon if not found
 */
export function getIconComponent(iconName: string): React.ComponentType<{ className?: string }> {
  return ICON_MAP[iconName] || IconSettings;
}

/**
 * Render an icon by name with className
 */
export function renderIcon(iconName: string, className: string = 'h-5 w-5') {
  const IconComponent = getIconComponent(iconName);
  return <IconComponent className={className} />;
}
